api_platform:
    title: 'My Application'
    description: 'Application description '
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Interfaces/Dto']
    swagger:
        api_keys:
            apiKey:
               name: Authorization
               type: header
