#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /user

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }